# Generated by Django 3.1.6 on 2021-04-07 00:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('answers', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=1000)),
                ('first_note', models.IntegerField(default=0)),
                ('second_note', models.IntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='intervalsApp.intervalsprofile')),
            ],
        ),
    ]
