# Generated by Django 3.1.6 on 2021-04-07 00:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0003_auto_20210406_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
