# Generated by Django 3.1.6 on 2021-04-11 02:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0004_auto_20210406_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalsprofile',
            name='recent_results',
        ),
        migrations.RemoveField(
            model_name='intervalsprofile',
            name='total_completed',
        ),
        migrations.RemoveField(
            model_name='intervalsprofile',
            name='total_correct',
        ),
        migrations.AddField(
            model_name='intervalsprofile',
            name='current_level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_results', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=20)),
                ('level', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervalsApp.intervalsprofile')),
            ],
        ),
    ]
