# Generated by Django 3.1.6 on 2021-04-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0005_auto_20210410_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentresults',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent', to='intervalsApp.intervalsprofile'),
        ),
    ]
