# Generated by Django 3.1.8 on 2021-04-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0006_auto_20210410_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentresults',
            name='level',
            field=models.IntegerField(),
        ),
    ]
