# Generated by Django 3.1.6 on 2021-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0007_auto_20210412_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalsprofile',
            name='note_order',
            field=models.CharField(choices=[('O', 'In Order'), ('B', 'Backwards'), ('R', 'Random')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='intervalsprofile',
            name='playback_speed',
            field=models.CharField(choices=[('S', 'Slow'), ('N', 'Normal'), ('F', 'Fast')], default='N', max_length=1),
        ),
    ]
