# Generated by Django 3.1.7 on 2021-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalsApp', '0008_auto_20210428_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
